# Generated by Django 2.2.13 on 2020-10-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('message_type', models.TextField(default='text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.TextField()),
                ('receiver', models.TextField()),
                ('room_id', models.TextField(default='p2p')),
            ],
        ),
    ]
