# Generated by Django 2.2.13 on 2020-10-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room_id',
            field=models.TextField(default='p2pchat'),
        ),
    ]
